development:
  adapter: postgresql
  encoding: utf8
  database: vcode_development
  pool: 5
  username: postgres
  password: 1bvb2fce3

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: vcode_test
  pool: 5
  username: postgres
  password: 1bvb2fce3

production:
  adapter: postgresql
  encoding: utf8
  database: vcode_production
  pool: 5
  username: postgres
  password: 1bvb2fce3